name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  fieldA:  # id of input
    description: 'test field A'
    required: true
    default: '1000'
  fieldB:
    description: 'test field B'

outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
